[Base]
ValueType=Float
DistCalcMethod=L2
IndexAlgoType=BKT
Dim=128
VectorPath=data/sift1m/sift/sift_base.fvecs
VectorType=XVEC
QueryPath=data/sift1m/sift/sift_query.fvecs
QueryType=XVEC
WarmupPath=data/sift1m/sift/sift_query.fvecs
WarmupType=XVEC
TruthPath=data/sift1m/sift/sift_groundtruth.ivecs
TruthType=XVEC
IndexDirectory=sift1m
; EnableBufferPool=true
; BufferPoolSize=2147483648
; BufferPoolEvictionPolicy=LRU
; BufferPoolHashTableExp=16
; BufferPoolEvictionRatio=0.1
[SelectHead]
isExecute=false

[BuildHead]
isExecute=false

[BuildSSDIndex]
isExecute=false

[SearchSSDIndex]
isExecute=true
BuildSsdIndex=false
InternalResultNum=32
SearchThreadNum=16
HashTableExponent=12
ResultNum=10
MaxCheck=2048
MaxDistRatio=8.0
SearchPostingPageLimit=12              
TmpDir=tempfolder/
UseSPDK=false
EnableBufferPool=false
BufferPoolSize=0
BufferPoolEvictionPolicy=LRU
BufferPoolHashTableExp=0               # 使用的哈希表指数
BufferPoolEvictionRatio=0.1            # 缓存淘汰比例
UseDirectIO=true                    # 启用直接 I/O
IOBatchSize=0                        # I/O 批处理大小
PreloadPages=0                     # 预加载页面数量

BufferPoolDebug=true
LogLevel=Info